# Site settings
title: Amy on GCP
# email: amy@infosleuth.net
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amygdala.github.io" # the base hostname & protocol for your site
twitter_username: amygdala
github_username:  amygdala

# Build settings
markdown: kramdown
highlighter: rouge

tag_page_layout: tag_page
tag_page_dir: tag
#tag_page_layout: tag
# tag_page_dir: blog/tags

gems:
- jekyll/tagging
- pygments.rb

tag_permalink_style: pretty
